DROP TABLE ODONTOLOGOS IF EXISTS;

CREATE TABLE ODONTOLOGOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMEROMATRICULA INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL
);
INSERT INTO ODONTOLOGOS VALUES (DEFAULT, '456789123', 'Lorena', 'Trujillo'),
(DEFAULT, '123456789', 'Lina', 'Gonzalez'),
(DEFAULT, '987654123', 'Pepito', 'Perez')